name: Build and Deploy
on:
  push:
    branches:
      -main

jobs:
  buid:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .Net6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Bulid
      run: dotnet build --configuration Release
    
